### ISSUE TITLE
Add public spec-z catalogs and training sets with real data

### ISSUE THREAD

**Issue by gschwend** [linea-it/pz-server-lib#40]
Upload the public compilation of spec-zs created for DES and the result of the cross-matching with DES DR2 on PZ Server.  Provide a QA notebook as an ancillary file.

Add compiled catalogs:

- [x]  public_specz_compilation
- [x]  public_pz_training_set  

Add individually (download from source and upload to PZ server as it is, without any cleaning): 

- [x]  2dFLenS
- [x]  3DHST
- [x]  DEEP2
- [x]  DEIMOS 10K
- [x]  GAMA
- [x]  GLASS
- [x]  SAGA
- [x]  SDSS
- [x]  VIPERS
- [x] zCOSMOS

 
| Survey  <br> (link to the website)| Number of redshifts in <be> the original sample | Reference <br> (link to the paper) |
|---|:-:|---|
| [2dFLenS](http://2dflens.swin.edu.au/) |70,079| [Blake et al. 2016](https://ui.adsabs.harvard.edu/abs/2016MNRAS.462.4240B/abstract)|
| [3DHST](http://3dhst.research.yale.edu/Data.php)|207,967|[Momcheva et al. 2016](https://ui.adsabs.harvard.edu/abs/2016ApJS..225...27M/abstract)|
|[DEEP2 (DR4)](http://deep.ps.uci.edu/DR4/home.html)|50,319|[Newman et al. 2013](https://ui.adsabs.harvard.edu/abs/2013ApJS..208....5N/abstract)|
|[DEIMOS 10K](http://cosmos.astro.caltech.edu/)|10,770|[Hasinger et al. 2018](https://ui.adsabs.harvard.edu/abs/2018ApJ...858...77H/abstract)| 
[GAMA (DR3) ](http://www.gama-survey.org/dr3/schema/table.php?id=24) |166,332 |[Baldry et al. 2018](https://ui.adsabs.harvard.edu/abs/2018MNRAS.474.3875B/abstract)  |
[GLASS (DR2)](https://archive.stsci.edu/prepds/glass/#dataformat) |3,289   |[Abramson et al. 2020](https://ui.adsabs.harvard.edu/abs/2020MNRAS.tmp..279A/abstract)|
[SAGA       ](http://sagasurvey.org/)|68,644 |[Geha et al. 2017       ](https://ui.adsabs.harvard.edu/abs/2017ApJ...847....4G/abstract)|
[SDSS (DR16)](http://www.sdss.org/dr16/)|4,613,773| [Ahumada et al. 2020    ](https://ui.adsabs.harvard.edu/abs/2020ApJS..249....3A/abstract)|  
[VIPERS     ](http://vipers.inaf.it/rel-pdr1.html)|91,507    |[Garilli et al. 2014    ](https://ui.adsabs.harvard.edu/abs/2014A%26A...562A..23G/abstract)|
[zCOSMOS    ](https://cesam.lam.fr/zCosmos/)|20,689    |[Lilly et al. 2009      ](https://ui.adsabs.harvard.edu/abs/2009ApJS..184..218L/abstract) <br> [Knobel et al. 2012](https://ui.adsabs.harvard.edu/abs/2012ApJ...753..121K/abstract) <br> [Lilly 2026 (DR description)](https://www.eso.org/sci/observing/phase3/data_releases/zcosmos_dr3_b2.pdf)|

```[tasklist]
### Tasks - 2dFLenS @gschwend
- [x] install pzserver library locally (or on JuputerHub)
- [x] create an API token for authentication
- [x] Start a new notebook (blank) and use the pzserver library to retrieve the spec-z catalog (public compilation) and filter the pandas dataframe to select only one survey at a time
- [x] create a new file containing the filtered dataset
- [x] upload this new dataset to PZ Server
- [x] create a new QA notebook (using the spec-z compilation as an example); the first cells should include access to the; corresponding dataset; don't forget to omit the token!
- [x] Execute and export the notebook results as HTML file
- [x] update the data product (Edit) to  include the HTML file with outputs and the `.ipynb` file without outputs
```

```[tasklist]
### Tasks - 3DHST @HeloisaMengisztki
- [x] install pzserver library locally (or on JuputerHub)
- [x] create an API token for authentication
- [x] Start a new notebook (blank) and use the pzserver library to retrieve the spec-z catalog (public compilation) and filter the pandas dataframe to select only one survey at a time
- [x] create a new file containing the filtered dataset
- [x] upload this new dataset to PZ Server
- [x] create a new QA notebook (using the spec-z compilation as an example); the first cells should include access to the; corresponding dataset; don't forget to omit the token!
- [x] Execute and export the notebook results as HTML file
- [x] update the data product (Edit) to  include the HTML file with outputs and the `.ipynb` file without outputs
```

```[tasklist]
### Tasks - DEEP2  @saraviz
- [x] install pzserver library locally (or on JuputerHub)
- [x] create an API token for authentication
- [x] Start a new notebook (blank) and use the pzserver library to retrieve the spec-z catalog (public compilation) and filter the pandas dataframe to select only one survey at a time
- [x] create a new file containing the filtered dataset
- [x] upload this new dataset to PZ Server
- [x] create a new QA notebook (using the spec-z compilation as an example); the first cells should include access to the; corresponding dataset; don't forget to omit the token!
- [x] Execute and export the notebook results as HTML file
- [x] update the data product (Edit) to  include the HTML file with outputs and the `.ipynb` file without outputs
```
```[tasklist]
### Tasks - DEIMOS 10K   @luigilcsilva
- [x] install pzserver library locally (or on JuputerHub)
- [x] create an API token for authentication
- [x] Start a new notebook (blank) and use the pzserver library to retrieve the spec-z catalog (public compilation) and filter the pandas dataframe to select only one survey at a time
- [x] create a new file containing the filtered dataset
- [x] upload this new dataset to PZ Server
- [x] create a new QA notebook (using the spec-z compilation as an example); the first cells should include access to the; corresponding dataset; don't forget to omit the token!
- [x] Execute and export the notebook results as HTML file
- [x] update the data product (Edit) to  include the HTML file with outputs and the `.ipynb` file without outputs
```
